import { Sparkles, Send, TrendingUp, AlertTriangle, CheckCircle } from "lucide-react";
import { useState } from "react";

const suggestedPrompts = [
  "Show me attrition risks",
  "Generate offer letter for John Doe",
  "Who's available for a new project?",
  "Compensation benchmark for engineers",
];

const recentInsights = [
  {
    icon: AlertTriangle,
    color: "text-orange-600",
    bg: "bg-orange-50",
    title: "High Attrition Risk",
    description: "Engineering team shows 23% risk in Q2",
    time: "2 hours ago",
  },
  {
    icon: TrendingUp,
    color: "text-green-600",
    bg: "bg-green-50",
    title: "Hiring Milestone",
    description: "5 candidates moved to final round",
    time: "4 hours ago",
  },
  {
    icon: CheckCircle,
    color: "text-blue-600",
    bg: "bg-blue-50",
    title: "Onboarding Complete",
    description: "3 employees successfully onboarded",
    time: "Yesterday",
  },
];

export function AIAssistant() {
  const [input, setInput] = useState("");

  return (
    <div className="h-full flex flex-col">
      {/* Header */}
      <div className="p-4 border-b border-gray-200">
        <div className="flex items-center gap-2 mb-1">
          <div className="w-8 h-8 bg-gradient-to-br from-blue-500 to-indigo-600 rounded-lg flex items-center justify-center">
            <Sparkles className="w-4 h-4 text-white" />
          </div>
          <h2 className="font-semibold text-gray-900">HR AI Agent</h2>
        </div>
        <p className="text-xs text-gray-500">Ask questions or get insights</p>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {/* Suggested Prompts */}
        <div>
          <h3 className="text-xs font-semibold text-gray-700 mb-2 uppercase tracking-wide">
            Suggested Prompts
          </h3>
          <div className="space-y-2">
            {suggestedPrompts.map((prompt, index) => (
              <button
                key={index}
                onClick={() => setInput(prompt)}
                className="w-full text-left px-3 py-2 bg-gray-50 hover:bg-gray-100 rounded-lg text-sm text-gray-700 transition-colors border border-gray-200"
              >
                {prompt}
              </button>
            ))}
          </div>
        </div>

        {/* Recent Insights */}
        <div>
          <h3 className="text-xs font-semibold text-gray-700 mb-2 uppercase tracking-wide">
            Recent AI Insights
          </h3>
          <div className="space-y-3">
            {recentInsights.map((insight, index) => {
              const Icon = insight.icon;
              return (
                <div
                  key={index}
                  className="p-3 bg-white border border-gray-200 rounded-lg hover:shadow-sm transition-shadow"
                >
                  <div className="flex items-start gap-3">
                    <div className={`${insight.bg} rounded-lg p-2`}>
                      <Icon className={`w-4 h-4 ${insight.color}`} />
                    </div>
                    <div className="flex-1 min-w-0">
                      <h4 className="text-sm font-medium text-gray-900 mb-0.5">
                        {insight.title}
                      </h4>
                      <p className="text-xs text-gray-600 mb-1">
                        {insight.description}
                      </p>
                      <span className="text-xs text-gray-400">
                        {insight.time}
                      </span>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* AI Generated Tag Example */}
        <div className="p-3 bg-gradient-to-br from-blue-50 to-indigo-50 rounded-lg border border-blue-100">
          <div className="flex items-center gap-2 mb-2">
            <Sparkles className="w-4 h-4 text-blue-600" />
            <span className="text-xs font-semibold text-blue-900">
              Auto-generated by AI
            </span>
          </div>
          <p className="text-xs text-gray-700 leading-relaxed">
            Team formation recommendations updated based on project requirements
            and employee availability.
          </p>
        </div>
      </div>

      {/* Input */}
      <div className="p-4 border-t border-gray-200 bg-white">
        <div className="flex items-end gap-2">
          <div className="flex-1">
            <textarea
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="Ask HR Agent anything..."
              rows={2}
              className="w-full px-3 py-2 bg-gray-50 border border-gray-200 rounded-lg text-sm resize-none focus:outline-none focus:ring-2 focus:ring-blue-500 focus:bg-white"
            />
          </div>
          <button className="p-2.5 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors">
            <Send className="w-4 h-4" />
          </button>
        </div>
      </div>
    </div>
  );
}
